apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: networking-project
  sources:
    - chart: pihole
      repoURL: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision: 2.24.0
      helm:
        valueFiles:
          - $git/pihole/charts/values.yaml
    - repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
      targetRevision: HEAD
      path: pihole/resources
      ref: git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: networking
  syncPolicy:
    automated:
      prune: true