apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: networking-project
  source:
    repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
    targetRevision: HEAD
    path: traefik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: networking
  syncPolicy:
    automated:
      prune: true