apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: networking-project
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 33.0.0
      helm:
        valueFiles:
          - $git/traefik/charts/values.yaml
    - repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
      targetRevision: HEAD
      path: traefik
      ref: git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: networking
  syncPolicy:
    automated:
      prune: true