apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unbound
  namespace: argocd
spec:
  project: networking-project
  sources:
    - chart: unbound 
      repoURL: https://pixelfederation.github.io/unbound
      targetRevision: 0.1.10
      helm:
        valueFiles:
          - $git/unbound/charts/values.yaml
    - repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
      targetRevision: HEAD
      path: unbound
      ref: git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: networking
  syncPolicy:
    automated:
      prune: true