---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: palworld-server
  name: palworld-server
  namespace: palworld-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: palworld-server
  template:
    metadata:
      labels:
        app: palworld-server
    spec:
      containers:
        - name: palworld-server
          image: thijsvanloef/palworld-server-docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8211
              name: server
              protocol: UDP
            - containerPort: 27015
              name: query
              protocol: UDP
          envFrom:
            - configMapRef: 
                name: palworld-cm
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: palworld-secrets
                  key: rconPassword
            - name: SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: palworld-secrets
                  key: serverPassword
          resources:
            requests:
              memory: "16Gi"
              cpu: "4000m"
          volumeMounts:
            - mountPath: /palworld
              name: datadir
              subPath: palworld-server
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: palworld-server-datadir
