apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: palworld-server
  name: palworld-persistent-volume
  namespace: palworld-server
spec:
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.187
    path: "/volume1/containers/palworld-server"