---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: palworld-server
  name: palworld-server
  namespace: palworld-server
spec:
  ports:
    - name: server
      port: 8211
      protocol: UDP
      targetPort: server
    - name: query
      port: 27015
      protocol: UDP
      targetPort: query
    - name: server-bryce
      port: 9211
      protocol: UDP
      targetPort: server
    - name: query-bryce
      port: 27016
      protocol: UDP
      targetPort: query
    - name: rest-api-bryce
      port: 9212
      targetPort: rest-api
  selector:
    app: palworld-server
  type: LoadBalancer
