---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: immich-psql
  name: immich-psql-svc
  namespace: immich
spec:
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
  selector:
    app: immich-psql