---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi