---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: github-runner
  name: github-runner-cm
  namespace: github-runner
data:
  ORGANIZATION: "monroe-shindelar-org"
  ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"