apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-sock-pv
  namespace: github-runner
  labels:
    app: github-runner
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/docker.sock"