kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-sock-pvc
  namespace: github-runner
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi