---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: overseerr
  name: overseerr
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi