---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teslamate-psql
  name: teslamate-psql-svc
  namespace: teslamate
spec:
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
  selector:
    app: teslamate-psql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teslamate
  name: teslamate-svc
  namespace: teslamate
spec:
  ports:
  - name: web
    port: 4000
    protocol: TCP
    targetPort: 4000
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: ClusterIP
  selector:
    app: teslamate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto-svc
  namespace: teslamate
spec:
  ports:
  - name: mosquitto
    port: 1883
    protocol: TCP
    targetPort: 1883
  type: ClusterIP
  selector:
    app: mosquitto
