apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-server
  namespace: argocd
spec:
  project: minecraft-server-project
  sources:
    - chart: minecraft
      repoURL: https://itzg.github.io/minecraft-server-charts/
      targetRevision: 4.23.6
      helm:
        valueFiles:
          - $git/minecraft-server/charts/values.yaml
    # - repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
      # targetRevision: HEAD
      # path: minecraft-server/resources
      # ref: git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minecraft-server
  syncPolicy:
    automated:
      prune: true