---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prowlarr
  name: prowlarr
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi