apiVersion: v1
kind: PersistentVolume
metadata:
  name: cs2-server-persistent-volume
  namespace: cs2-server
spec:
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.187
    path: "/volume1/containers/cs2-server"