apiVersion: v1
kind: PersistentVolume
metadata:
  name: cs2-server-persistent-volume
  namespace: cs2-server
spec:
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  nfs:
    server: synology-service.filesystem.svc.cluster.local
    path: "/volume1/containers/cs2-server"