---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cs2-server
  name: cs2-server-datadir
  namespace: cs2-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

