apiVersion: v1
kind: Service
metadata:
  labels:
    app: cs2-server
  name: cs2-server
  namespace: cs2-server
spec:
  ports:
    - name: "server"
      port: 27015
      targetPort: 27015
    - name: "server-udp"
      port: 27015
      protocol: UDP
      targetPort: 27015
    - name: "tv"
      port: 27017
      protocol: UDP
      targetPort: 27017
    - name: "27026"
      port: 27016
      protocol: UDP
      targetPort: 27016
  selector:
    app: cs2-server
  type: LoadBalancer
