apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: get5
  namespace: argocd
spec:
  project: get5-project
  source:
    repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
    targetRevision: HEAD
    path: get5
  destination:
    server: "https://kubernetes.default.svc"
    namespace: get5
  syncPolicy:
    automated:
      prune: true