apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: palworld-server
  namespace: argocd
spec:
  project: palworld-server-project
  source:
    repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
    targetRevision: HEAD
    path: palworld-server
  destination:
    server: "https://kubernetes.default.svc"
    namespace: palworld-server
  syncPolicy:
    automated:
      prune: true
