---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: synology
  name: synology-service
  namespace: filesystem
subsets:
- addresses:
  - ip: 10.2.0.10
  ports:
  - name: dsm
    port: 5000
    protocol: TCP
  - name: dsm-https
    port: 5001
    protocol: TCP
  - name: qbt
    port: 9865
    protocol: TCP