apiVersion: v1
kind: Service
metadata:
  labels:
    app: synology
  name: synology-service
  namespace: filesystem
spec:
  ports:
  - name: synology
    port: 5000
    targetPort: synology
    protocol: TCP
