apiVersion: v1
kind: Service
metadata:
  labels:
    app: synology
  name: synology-service
  namespace: filesystem
spec:
  ports:
  - name: dsm
    port: 5000
    targetPort: dsm
    protocol: TCP
  - name: dsm-https
    port: 5001
    targetPort: dsm-https
    protocol: TCP
  - name: qbt
    port: 9865
    targetPort: qbt
    protocol: TCP
