apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: get5-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project for Get5
  destinations:
  - namespace: get5
    server: https://kubernetes.default.svc
    name: in-cluster
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
