apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-sync
  namespace: pihole
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: nebula-sync
  template:
    metadata: 
      labels: 
        app: nebula-sync
    spec:
      containers:
        - name: nebula-sync
          image: ghcr.io/lovelaze/nebula-sync:latest
          envFrom:
            - configMapRef:
                name: nebula-env
          env:
            - name: PIHOLE_PASS
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: adminPassword
            - name: PRIMARY
              value: "http://pihole-0.pihole-headless.pihole.svc.cluster.local|$(PIHOLE_PASS)"
            - name: REPLICAS
              value: "http://pihole-1.pihole-headless.pihole.svc.cluster.local|$(PIHOLE_PASS)"
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
