apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collection
  namespace: argocd
spec:
  project: collection-project
  source:
    repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
    targetRevision: HEAD
    path: collection
  destination:
    server: "https://kubernetes.default.svc"
    namespace: collection
  syncPolicy:
    automated:
      prune: true