---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi