apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  ports:
    - name: web
      port: 8123
      targetPort: 8123
  selector:
    app: homeassistant
  type: LoadBalancer