---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rust-server
  name: rust-server
  namespace: rust-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
