apiVersion: v1
kind: Service
metadata:
  labels:
    app: rust-server
  name: rust-server
  namespace: rust-server
spec:
  ports:
    - name: "server"
      port: 28015
      targetPort: 28015
    - name: "server-udp"
      port: 28015
      protocol: UDP
      targetPort: 28015
    - name: "rcon"
      port: 28016
      protocol: UDP
      targetPort: 28016
  selector:
    app: rust-server
  type: LoadBalancer
