apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-iii
  namespace: argocd
spec:
  project: firefly-iii-project
  sources:
    - chart: firefly-iii-stack
      repoURL: https://firefly-iii.github.io/kubernetes/ 
      targetRevision: 0.8.8
      helm:
        valueFiles:
          - $git/firefly-iii/charts/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: firefly-iii
  syncPolicy:
    automated:
      prune: true