apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology
  namespace: argocd
spec:
  project: filesystem-project
  source:
    repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
    targetRevision: HEAD
    path: synology
  destination:
    server: "https://kubernetes.default.svc"
    namespace: filesystem
  syncPolicy:
    automated:
      prune: true