apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner
  namespace: argocd
spec:
  project: github-runner-project
  sources:
    - repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
      targetRevision: HEAD
      path: github-runner
      ref: git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: github-runner
  syncPolicy:
    automated:
      prune: true