---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: bluesky-pds
  name: bluesky-cm
  namespace: bluesky
data:
  PDS_HOSTNAME: bsky.jevn.sex
  PDS_DB_SQLITE_LOCATION: /pds/pds.sqlite
  PDS_BLOBSTORE_DISK_LOCATION: /pds/blocks
  PDS_DID_PLC_URL: https://plc.bsky-sandbox.dev
  PDS_BSKY_APP_VIEW_ENDPOINT: https://api.bsky-sandbox.dev
  PDS_BSKY_APP_VIEW_DID: did:web:api.bsky-sandbox.dev
  PDS_CRAWLERS: https://bgs.bsky-sandbox.dev