apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluesky-pds
  name: bluesky-pds
  namespace: bluesky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluesky-pds
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bluesky-pds
    spec:
      containers:
        - image: ghcr.io/bluesky-social/pds:0.4
          name: bluesky-pds
          ports:
            - name: pds
              containerPort: 3000
          envFrom:
            - configMapRef: 
                name: bluesky-cm
          env:
            - name: PDS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bluesky-secret
                  key: adminPassword
            - name: PDS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bluesky-secret
                  key: jwtSecret
            - name: PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: bluesky-secret
                  key: repoSigningKey
            - name: PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: bluesky-secret
                  key: rotationKey
          volumeMounts:
            - mountPath: /pds
              name: bluesky-pds-datadir
              subPath: bluesky-pds
      restartPolicy: Always
      volumes:
        - name: bluesky-pds-datadir
          persistentVolumeClaim:
            claimName: bluesky-pds
