---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bluesky-pds
  name: bluesky-pds
  namespace: bluesky
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi