apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd-project
  sources:
    - chart: argocd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/argocd/charts/values.yaml
    - repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
      targetRevision: HEAD
      path: argocd/resources
      directory:
        recurse: true
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
