apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-persistent-volume
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /volume1/containers/grafana
    server: 10.0.0.187