---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana-server
  name: grafana-datadir
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""