apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: media-project
  sources:
    - chart: plex-media-server
      repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
      targetRevision: 0.4.0
      helm:
        valueFiles:
          - $git/plex/charts/values.yaml
    - repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
      targetRevision: HEAD
      path: plex/resources
      ref: git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: media
  syncPolicy:
    automated:
      prune: true