apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-persistent-volume
  namespace: networking
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.187
    path: "/volume1/containers/pihole"