apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: media-project
  sources:
    - chart: jellyfin
      repoURL: https://jellyfin.github.io/jellyfin-helm
      targetRevision: 2.1.0
      helm:
        valueFiles:
          - $git/jellyfin/charts/values.yaml
    - repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
      targetRevision: HEAD
      path: jellyfin
      ref: git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: media
  syncPolicy:
    automated:
      prune: true