---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: g5
  name: g5-mysql
  namespace: get5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi