---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bazarr
  name: bazarr
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi