---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lidarr
  name: lidarr
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi