apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rust-server
  namespace: argocd
spec:
  project: rust-server-project
  source:
    repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
    targetRevision: HEAD
    path: rust-server
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rust-server