---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ddclient
  name: ddclient
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
