--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: firefly-iii-db
  name: firefly-iii-db
  namespace: firefly-iii
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: firefly-iii
  name: firefly-iii
  namespace: firefly-iii
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 25Gi