apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: valheim-server
  name: valheim-persistent-volume
  namespace: valheim-server
spec:
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.187
    path: "/volume1/containers/valheim-server"