---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: valheim-server
  name: valheim-server-datadir
  namespace: valheim-server
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi